; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags =
    -DICM45686
    ;-DAPEX_DEBUG        ; human-readable serial — swap for -DAPEX_PLOT to use monitor
     -DAPEX_PLOT       ; structured output for apex/sim/scripts/monitor.py
lib_deps =
    https://github.com/sparkfun/SparkFun_BMP581_Arduino_Library
    adafruit/Adafruit ADXL375
    tdk-invn-oss/ICM45686
    https://github.com/sparkfun/SparkFun_MMC5983MA_Magnetometer_Arduino_Library
    paulstoffregen/Mahony
    sparkfun/SparkFun u-blox GNSS v3
